### ISSUE TITLE
Highlighter must sync its size to textarea on focus

### ISSUE THREAD

**Issue by ivirabyan** [ivirabyan/jquery-mentions#16]

**Comment by mattlacey** [comment]
Does this cause the highlighter to be only a few pixels high at times? Checked the styling and height was 0 after I inserted a mention, temporarily fixed with "min-height: 2em;".

My textarea is not visible when the plugin is initialised.

**Comment by ivirabyan** [comment]
It might be, I don't remember the problem behind this. What browser you use?

**Comment by ivirabyan** [comment]
Just noticed that your textarea is not visible upon initialization. That's the root of the problem. You should initialize the plugin once the textarea is visible, otherwise highlighter may not work correctly (since it tries to mimic appearance of the textarea).

**Comment by mattlacey** [comment]
Ah ok, that makes sense, will try and get that sorted out! It's a great plugin, working really well for my use case!

**Comment by ivirabyan** [comment]
Thanks for the feedback

**Comment by realdem** [comment]
I also have trouble with my highlighter, but it's acting differently. It moves the background-of-the-box upward. I made a new issue page for this. I'm also letting you know, here as well. [Here's my issue](https://github.com/ivirabyan/jquery-mentions/issues/48)

**Comment by ivirabyan** [comment]
Closing as non relevant anymore
