### ISSUE TITLE
Weird character after mentions

### ISSUE THREAD

**Issue by calbertuk** [ivirabyan/jquery-mentions#17]
I get this character after every mention which I haven't managed to remove 
![d](http://puu.sh/eON9N/c6cce9a0fb.png)

and it shows as a question mark when I output it:

![d](http://puu.sh/eONdf/713d97cbbf.png)

Apparently, it's a character Chrome can't display (see http://stackoverflow.com/questions/23511275/json-response-format-error-red-dot-bullet-before-response)

char var dump returns this: "ï»¿"

Any thoughts on why this is happening?

**Comment by ivirabyan** [comment]
This character is used internally to keep track of mentions in textarea. You probably getting textarea's value directly, instead of using methods, which causes such an issue.

**Comment by calbertuk** [comment]
Actually, I use getMentions and getValue which returns this
![de](http://puu.sh/eOPOv/a784b5e4ec.png)

where content is the raw content of my textarea (which is the string I store in my database).

I guess I'll just do some str_replace on it.

Thanks

**Comment by ivirabyan** [comment]
You shouldn't be using raw content of the textarea. Use `getRawValue` instead.

**Comment by calbertuk** [comment]
It's not listed as a method so didn't know it was a thing!

That will help, thank you!

**Comment by ivirabyan** [comment]
I just added it. Your use case is little different from mine, so I didn't have it before

**Comment by calbertuk** [comment]
Thank you!
