### ISSUE TITLE
Callback for completed insertion

### ISSUE THREAD

**Issue by JonFabritius** [ivirabyan/jquery-mentions#19]
I have a situation where my wysiwyg editor (Redactor 10) fails to immediately sync a newly inserted mention into its underlying textarea. The mention result appears correctly in the contenteditable div, but doesn't update in the hidden textarea until a keypress is performed, to add a space, for example.

I tried utilizing ui-autocomplete callbacks, such as close and change, but they seem to be not supported in jquery-mentions? (Or I have bad jquery-fu) On the other end, I tried forcing Redactor to sync. No luck.

The simplest and generally useful fix could be some kind of 'all done' callback for when an item has successfully been inserted into the input? (I can then improvise a sync from there on)

**Comment by ivirabyan** [comment]
I also use Redactor editor with mentions and had such a problem. Every time a mention is inserted `change` event gets triggered on the editor, so you can use it to call `sync` method on your editor.
Here is a snippet from my code, it's CoffeeScript but should be clear enough:
```
RedactorPlugins.mentions =
    init: ->
        @$editor.mentionsInput {source: '/mentions/autocomplete/', showAtCaret: true}
        @$editor.on 'change.mentionsInput', (e) =>
            @sync()
```

**Comment by JonFabritius** [comment]
Thanks, worked like a charm.
