### ISSUE TITLE
Thanks so much and a commit

### ISSUE THREAD

**Issue by brandonhall** [ivirabyan/jquery-mentions#20]
Thanks so much for redoing this plugin. It was in need of some love and I'm glad you provided it. I was working through it and added a couple of things if you want to grab them: https://github.com/brandonhall/jquery-mentions/commit/5a800fb4fec8f811c52817d6190567797fb1122b

I didn't deal with a pull request because they are simple and I don't use CoffeeScript.

**Comment by ivirabyan** [comment]
I left some comments on your commit, take a look.

**Comment by brandonhall** [comment]
I responded to your comments. There's probably a cleaner way to do the icon part but I thought it was useful for icon font libraries.

**Comment by ivirabyan** [comment]
We've now have separated issues, closing
