### ISSUE TITLE
Mention callback

### ISSUE THREAD

**Issue by avdept** [ivirabyan/jquery-mentions#24]
Is there any callback that fires after you select mentioned object? I want to modify its appearance in my textarea

**Comment by ivirabyan** [comment]
There is no such callback, and I can't imagine how it can be useful. Can you provide more details on what exactly you want to modify, maybe it can be done in some other way.

**Comment by avdept** [comment]
Sure. For ex. i want use method setValue(value), to modify appearance in my textarea from `<strong>Value</strong`, to something like `<span data-thing="Some Cool Stuff here">Value</span>`

At the moment i simply went to plugin code and changed behavior of function `mentionTpl` to what i need. But changing source of plugin doesnt seem good idea for me though

**Comment by ivirabyan** [comment]
So, you're using contenteditable, not textarea. And you want to insert `span` tag instead of `strong`. And probably add some data attribute to it (which would always have the same value). I can make `mentionTpl` configurable, but it is still not clear for me why would one want to do this.

**Comment by avdept** [comment]
Yes. I'm using with contenteditable(imperavi - redactor js). I want this because i have redmine plugin, which parses text from redactor and does some actions. I might send pull request if i decide to add some flexibility to `mentionTpl`.


Also i have strange behavior of plugin itself

I have code calling plugin:

````$(function(){
    console.log('fired');
    $('.redactor-editor').mentionsInput({source: function(request, response){
        console.log(request);
        project_id = $('form').first().attr('action').replace( /\/projects\//, '' );
      project_id = project_id.replace( /\/search/, '' );
      $.ajax({
        url: '/mention/search',
        data: {'search_tag': request, project_id: project_id},
        success: function(result) {
            console.log(result);
          response(result['users'])
        }
      });
    }})
});````
