### ISSUE TITLE
Define package version

### ISSUE THREAD

**Issue by pmichna** [ivirabyan/jquery-mentions#29]
Please, define versioning for this repository. It would helpful for creating a rails asset (https://rails-assets.org/).

**Comment by ivirabyan** [comment]
I'm not familiar with rails, can you submit pull request with required changes?

**Comment by pmichna** [comment]
This is a pure repository issue - no rails required. :)
https://help.github.com/articles/creating-releases/

**Comment by ivirabyan** [comment]
Oh, now I get it
