### ISSUE TITLE
Creating a new mention before an already existing mention removes all mentions after it

### ISSUE THREAD

**Issue by zilions** [ivirabyan/jquery-mentions#35]
If I create a mention and then another mention before that original mention, the original mention is removed.

For example, if my textbox has the following ("TestingTest" being the mention):

`Hello, this is an example TestingTest.`

If I then go back to the start of the textarea to add in another mention, the first mention, being "TestingTest" is removed and is then displayed like normal text without the styling.
For example, if I add a new mention (called "NewMention") before the original:

`Hello NewMention, this is an example TextingTest.`

"NewMention" will have the correct styling, although the original mention, "TestingTest" does not.

**Comment by kmgalanakis** [comment]
Hi! I also noticed this kind of misbehaviour. Could you please fix this issue? Regards
