### ISSUE TITLE
Does jquery-mentions support TinyMCE?

### ISSUE THREAD

**Issue by mdburgos** [ivirabyan/jquery-mentions#40]
The documentation states that this plugin supports WYSIWYG editors, but I'm having troubles trying to make it work with TinyMCE.

Is there something additional I need to do in order to make it work or is it a bug? It works fine for simple textareas

**Comment by mdburgos** [comment]
Closing this one since according to this https://github.com/ivirabyan/jquery-mentions/issues/9 it does support any WYSIWYG editor. I haven't been able to make it work with TinyMCE though

**Comment by ivirabyan** [comment]
Basicaly, you have to apply jqueryMentions to div with `contenteditable="true"`. 
I just checked TinyMCE, it creates editable area inside of `iframe`, that prevents plugin from working correctly.

**Comment by mdburgos** [comment]
Thanks for the clarification, it was helpful.
