### ISSUE TITLE
Show the drop-down on top of the focused input/textarea

### ISSUE THREAD

**Issue by valentinjurca** [ivirabyan/jquery-mentions#41]
Is it posible to show the drop-down list on top of the focused input? My desired input/textarea is fixed to the bottom of the screen and I wish the options to be visible anyway.
![example](https://cloud.githubusercontent.com/assets/10044331/9439275/19b05d3e-4a6e-11e5-9e78-18ce11eb3874.png)

**Comment by ivirabyan** [comment]
You, you can do this using option `position` for autocomplete plugin:
```
        $('.mentions').mentionsInput({
            autocomplete: {
                position: { my: "left bottom", at: "left top" }
           }
        })
```

**Comment by Declie** [comment]
Is there a way to position the dropdown at the caret position in the textarea? The above solution seems to position the dropdown in relation to the textarea itself...
