### ISSUE TITLE
Apostrophes getting converted to html entity

### ISSUE THREAD

**Issue by amerikan** [ivirabyan/jquery-mentions#45]
When I use `it's` in the mention text area, it'll become `it&#39;s`. Is that expected behavior? I really don't want that to happen.

**Comment by ivirabyan** [comment]
It is not intended to be visible to user or to be exposed via `getValue()`.
Where exactly do you see `&#39;` ?

**Comment by amerikan** [comment]
I have this:
```js
var post = $('textarea#user_post').mentionsInput('getValue');
alert(post);
```

If I type in a `'` in the textarea such as "It's time!" it gets converted to `It&#39;s time!`.

![screen shot 2015-12-15 at 9 58 49 am](https://cloud.githubusercontent.com/assets/179356/11819077/e028a10e-a312-11e5-9e71-d087861d6b61.png)

**Comment by amerikan** [comment]
@ivirabyan here's an update. First I think in `master` jquery.mentions.coffee` and `jquery.mentions.js` are not in sync.

The bug mentioned above was present in v1.0.1. If I use the .js file from master, the bug is not present.

**Comment by amerikan** [comment]
I would recommend releasing a new version so people can get latest version and not the v1.0.1 which has that bug, which to me is not a forgivable bug.

**Comment by ivirabyan** [comment]
I have made a new release v1.0.2

**Comment by amerikan** [comment]
Thanks!
