### ISSUE TITLE
Add space character at the end of a mention

### ISSUE THREAD

**Issue by amerikan** [ivirabyan/jquery-mentions#46]
Currently after adding a mention the cursor stays at the end of the mention text. I think it would be nice to add space after adding a mention. 

For example (I'm using _ to denote the cursor), if I add a mention this happens `@alex_`, but it would be better for it to behave this way `@alex  _`. Does that make sense?

I propose this because after adding a mention I find myself ***always*** adding a space after to continue typing.

**Comment by amerikan** [comment]
@ivirabyan I was about to to implement this (I have limited coffeescript experienc), but I noticed that the .js file does not match some of the stuff in the .coffee file. Can you generate the .js from latest .coffee file and commit? Thanks!

**Comment by ivirabyan** [comment]
It's a nice feature, but it must be optional (although true by default).

**Comment by ivirabyan** [comment]
Now you can pass option `suffix: " "` to automatically add a space after mention

**Comment by amerikan** [comment]
I downloaded v1.0.3 from releases (https://github.com/ivirabyan/jquery-mentions/releases/tag/1.0.3), however, this feature was not on there. Did you forget to compile the .coffee?

If I grab the .js from the master branch (https://github.com/ivirabyan/jquery-mentions/blob/master/jquery.mentions.js), it works. Something is out of sync?

**Comment by ivirabyan** [comment]
I made v1.0.4 release which includes this feature
