### ISSUE TITLE
The jQuery makes my input box fall apart. I've tried fixing it repeatedly.

### ISSUE THREAD

**Issue by realdem** [ivirabyan/jquery-mentions#48]
When I turn on the mentions on my input box: [**it looks like this!**](https://drive.google.com/open?id=0B1NUzGelLgowUjN5VVZmWjBnd3c)
(The image I linked is of my input box with a correctly positioned focus region. However, the display of the white-box which-is-the input style gets moved up several pixels. What is wrong here??

What can I do to combat the stylizing ... which is probably on the highlighter box that your code creates. I love this mentions ability and I would love to continue using it. 
Can you help me with this?

**Comment by ivirabyan** [comment]
It would be good if you created standalone example I can experiment with. And yes, most likely there are some issues with highlighter styling, which is based on input box styling.

**Comment by realdem** [comment]
Hey, it's been a few weeks since I brought this up. I hope the suspense has been killin' ya haha. 
I fixed my error. It was a CSS rule which was way up the hierarchy and messed with the input box. Fixed. You might want to close this issue now; I do have another question which I will create another issue for shortly. Thanks for keeping this page alive, btw.
