### ISSUE TITLE
Disable Helper Text

### ISSUE THREAD

**Issue by varun-raj** [ivirabyan/jquery-mentions#55]
How can I disable the default helper text given by jQuery UI Autocomplete.

`2 results are available, use up and down arrow keys to navigate`

**Comment by ivirabyan** [comment]
This helper text shouldn't be visible, it is only used for screen readers. Seems like you don't included corresponding styles to your project.
Jquery UI stylesheets contain this style:
```
.ui-helper-hidden-accessible {
    border: 0;
    clip: rect(0 0 0 0);
    height: 1px;
    margin: -1px;
    overflow: hidden;
    padding: 0;
    position: absolute;
    width: 1px;
}
```
