### ISSUE TITLE
Highlight matched text

### ISSUE THREAD

**Issue by rept** [ivirabyan/jquery-mentions#57]
Hi,

Thx for your library, works really well.  In the backend (through ajax) I'm matching results case-insensitive (by doing LOWER in DB).  I noticed however that in the front end, it will only highligh matched substrings in bold if the case is exactly the same.  Is there a way to change this?

Another minor question: is there a way to only trigger the request to the server after minimum 2 chars?

**Comment by ivirabyan** [comment]
I fixed this issue in master branch.

On second question: yes, you can set `minLength` option of `jquery.autocomplete` widget:
`mentionsInput({autocomplete: {minLength: 2}})`
