### ISSUE TITLE
Multiple Trigger Chars

### ISSUE THREAD

**Issue by ngaurav** [ivirabyan/jquery-mentions#60]
I have two source of data. I want to use '@' for mentions ans '#' for hashtags.
Is this possible right now?

I found these links which are relevant here
[Support Multiple Trigger Chars by ryanramage · Pull Request #7](https://github.com/podio/jquery-mentions-input/pull/7/commits)
[ryanramage fork](https://github.com/ryanramage/jquery-mentions-input/commit/4fe4f80c904d2700efb848eca0615c7a4c10d08f)

**Comment by ivirabyan** [comment]
That's not possible out of the box.
If you just need to autocomplete hashtags typed by the user, you don't need such a complex plugin. Try using [jquery-textcomplete](https://github.com/yuku-t/jquery-textcomplete) for hashtags.

**Comment by ivirabyan** [comment]
You can set multiple trigger chars, settings trigger='@#', but plugin will use the same datasource for both chars.
