### ISSUE TITLE
Can't put two mentions consecutively without a space

### ISSUE THREAD

**Issue by fallXone** [ivirabyan/jquery-mentions#65]
In the example, try to mention two things like this @alex@angrybirds. You will notice that alex becomes a mention, but the dropdown will never appear for @angrybirds unless you put a space after alex

**Comment by ivirabyan** [comment]
I think this is a correct behaviour, since in your case '@' is a part of a word. Suppose you have autocomplete for emails: then user@example.com should not try to autocomplete "@example.com" part.

**Comment by fallXone** [comment]
I think you bring up a valid point, but what about the example in which you press enter (or click) to select an item from the dropdown. At that point, the tag is confirmed, and thus you should be able to start tagging again, regardless of a space.

**Comment by ivirabyan** [comment]
ok, I think we can just get rid of this restriction. Anyway, would be great to see a real world example of such a case.
