### ISSUE TITLE
getValue add extra character behind the value.

### ISSUE THREAD

**Issue by chiragsatapara** [ivirabyan/jquery-mentions#67]
Get Value add some extra character after the mention value , here look the image. [Click here](https://i.stack.imgur.com/CxPDW.png) , red dot indicate the extra character , it save ? into the database.
@ivirabyan

**Comment by ivirabyan** [comment]
Do use ordinary textarea or contenteditable?

**Comment by chiragsatapara** [comment]
I am using a contenteditable

**Comment by chiragsatapara** [comment]
$('#editable').mentionsInput('getValue'); this value return the data which contain `u200B` , so i use this function to remove that. `.replace(/[\u200B-\u200D\uFEFF]/g, '')` and now it is working fine , so you have to think on this .

**Comment by chiragsatapara** [comment]
this character are zero width character . Refer this stackoverflow link [click here](http://stackoverflow.com/questions/11305797/remove-zero-width-space-characters-from-a-javascript-string)

**Comment by ivirabyan** [comment]
Yes, I know about this character, it's required for mentions to work properly. Of course  this shouln't  be returned with getValue() call, it's only part of representation, not what actually must be stored.

**Comment by chiragsatapara** [comment]
@ivirabyan, it is return with the getValue() , so i just do below change in my code.

```
 MentionsContenteditable.prototype.getValue = function() {
      var markupMention, value;
      value = this.input.clone();
      markupMention = this._markupMention;
      $(this.selector, value).replaceWith(function() {
        var name, uid;
        uid = $(this).data('mention');
        name = $(this).text();
        return markupMention({
          name: name,
          uid: uid
        });
      });
      return value.html().replace(this.marker, '').replace(/[\u200B-\u200D\uFEFF]/g, '');
    };
```
